from __future__ import absolute_import
import json

from rest_framework.response import Response

from sentry import options
from sentry.api.bases.project import ProjectEndpoint
from sentry.models import Event, SnubaEvent


# from sentry.api.permissions import ScopedPermission


class StackExchangeEndpoint(ProjectEndpoint):
    # TODO(dashed): what's this? is this necessary?
    # permission_classes = (ScopedPermission, )

    def get(self, request, project, event_id):
        # TODO: add docstrings

        use_snuba = options.get('snuba.events-queries.enabled')

        event_cls = SnubaEvent if use_snuba else Event

        event = event_cls.objects.from_event_id(event_id, project.id)
        if event is None:
            return Response({'detail': 'Event not found'}, status=404)

        exception_interface = event.get_interface('exception')

        exception_string = exception_interface.to_string(event)

        if not exception_string:
            return Response({'detail': 'No results'}, status=404)

        exception_string = exception_string.splitlines()[0].strip()

        # for interface in six.itervalues(event.interfaces):
        #     import logging
        #     logging.info("interface: %s", interface.to_string(event))
        #     exception_body = interface.to_email_html(event)

        import logging
        logging.info("exception: %s", exception_string)

        return Response(thing, status=200)


thing = json.loads('{"items":[{"tags":["python","python-2.7"],"owner":{"reputation":104,"user_id":8280454,"user_type":"registered","accept_rate":20,"profile_image":"https://www.gravatar.com/avatar/030971d103cd0b8128440041bfd2af9f?s=128&d=identicon&r=PG&f=1","display_name":"A.S","link":"https://stackoverflow.com/users/8280454/a-s"},"is_answered":false,"view_count":312,"answer_count":1,"score":1,"last_activity_date":1561419298,"creation_date":1530282436,"question_id":51103947,"link":"https://stackoverflow.com/questions/51103947/excel-application-workbooks-attribute-error-when-converting-excel-to-pdf","title":"Excel.Application.Workbooks attribute error when converting excel to pdf"},{"tags":["python","python-3.x","pip","pyomo"],"owner":{"reputation":1,"user_id":5868113,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/d545b1c5f638adeee37945b021461f8e?s=128&d=identicon&r=PG&f=1","display_name":"Presti","link":"https://stackoverflow.com/users/5868113/presti"},"is_answered":false,"view_count":14,"answer_count":0,"score":0,"last_activity_date":1561417294,"creation_date":1561417294,"question_id":56744935,"link":"https://stackoverflow.com/questions/56744935/attributeerror-module-pip-has-no-attribute-logging","title":"AttributeError: Module &#39;pip&#39; has no attribute &#39;logging&#39;"},{"tags":["python","python-3.x","beautifulsoup"],"owner":{"reputation":1,"user_id":11605878,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/01477d921646ea1cf3e0ca95bb5586bb?s=128&d=identicon&r=PG&f=1","display_name":"facsasd","link":"https://stackoverflow.com/users/11605878/facsasd"},"is_answered":true,"view_count":34,"answer_count":1,"score":0,"last_activity_date":1561416685,"creation_date":1561411076,"last_edit_date":1561416685,"question_id":56744083,"link":"https://stackoverflow.com/questions/56744083/attributeerror-str-object-has-no-attribute-descendants-error-when-using-bea","title":"AttributeError: &#39;str&#39; object has no attribute &#39;descendants&#39; error when using BeautifulSoup"},{"tags":["python","tensorflow","attributes"],"owner":{"reputation":1,"user_id":11694667,"user_type":"registered","profile_image":"https://lh6.googleusercontent.com/-PgiIJnOvgNM/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfh8vGf4l61WZA3THTC60d2sJzCQA/photo.jpg?sz=128","display_name":"shivesh kumar","link":"https://stackoverflow.com/users/11694667/shivesh-kumar"},"is_answered":false,"view_count":8,"answer_count":0,"score":0,"last_activity_date":1561416185,"creation_date":1561415803,"last_edit_date":1561416185,"question_id":56744759,"link":"https://stackoverflow.com/questions/56744759/module-tensorflow-has-no-attribute","title":"Module &#39;tensorflow&#39; has no attribute"},{"tags":["python","mongoengine"],"owner":{"reputation":43,"user_id":6353501,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/d672032266d75ee78744e4b6f7f53306?s=128&d=identicon&r=PG&f=1","display_name":"A.Mahamedi","link":"https://stackoverflow.com/users/6353501/a-mahamedi"},"is_answered":false,"view_count":8,"answer_count":0,"score":0,"last_activity_date":1561414627,"creation_date":1561414627,"question_id":56744603,"link":"https://stackoverflow.com/questions/56744603/listfieldreferencefieldx-query-mongoengine","title":"ListField(ReferenceField(x)) query mongoengine"},{"tags":[".net","ironpython","spotfire"],"owner":{"reputation":3,"user_id":11666904,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/56ef2db54ce36c90dcf289184cfc32ba?s=128&d=identicon&r=PG&f=1","display_name":"harro","link":"https://stackoverflow.com/users/11666904/harro"},"is_answered":false,"view_count":4,"answer_count":0,"score":0,"last_activity_date":1561410396,"creation_date":1561408595,"last_edit_date":1561410396,"question_id":56743620,"link":"https://stackoverflow.com/questions/56743620/htmltextarea-object-has-no-attribute-exporttext","title":"HtmlTextArea&#39; object has no attribute &#39;ExportText"},{"tags":["python","tcp","pyshark"],"owner":{"reputation":1,"user_id":9905248,"user_type":"registered","profile_image":"https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=128","display_name":"Kevin","link":"https://stackoverflow.com/users/9905248/kevin"},"is_answered":false,"view_count":5,"answer_count":0,"score":0,"last_activity_date":1561409372,"creation_date":1561409372,"question_id":56743757,"link":"https://stackoverflow.com/questions/56743757/pyshark-packet-tcp-analysis-ack-rtt-not-consistently-available","title":"Pyshark packet.tcp.analysis_ack_rtt not consistently available"},{"tags":["python","kivy","kivy-language"],"owner":{"reputation":8,"user_id":11489598,"user_type":"registered","profile_image":"https://graph.facebook.com/2346150315405059/picture?type=large","display_name":"Sam Bennett","link":"https://stackoverflow.com/users/11489598/sam-bennett"},"is_answered":false,"view_count":15,"answer_count":1,"score":1,"last_activity_date":1561408331,"creation_date":1561406266,"last_edit_date":1561406961,"question_id":56743156,"link":"https://stackoverflow.com/questions/56743156/kivy-attributeerror-label-object-has-no-attribute-a","title":"Kivy: AttributeError: &#39;Label&#39; object has no attribute &#39;a&#39;"},{"tags":["python","tensorflow","lambda","keras","layer"],"owner":{"reputation":11,"user_id":11693382,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/b52f3b2bba7d65d7d246253ac0cdb14e?s=128&d=identicon&r=PG&f=1","display_name":"Ehsan","link":"https://stackoverflow.com/users/11693382/ehsan"},"is_answered":false,"view_count":12,"answer_count":2,"score":2,"last_activity_date":1561405850,"creation_date":1561396037,"question_id":56741098,"link":"https://stackoverflow.com/questions/56741098/error-in-keras-lambda-layer-while-adding-or-multiplying-with-constant-non-tenso","title":"Error in Keras&#39; lambda layer while adding or multiplying with constant non-tensor numbers"},{"tags":["python","pandas","plotly","data-visualization","plotly-dash"],"owner":{"reputation":38,"user_id":7872144,"user_type":"registered","accept_rate":67,"profile_image":"https://www.gravatar.com/avatar/582195df62ae389f5190c99d28759d95?s=128&d=identicon&r=PG&f=1","display_name":"M. Vlad","link":"https://stackoverflow.com/users/7872144/m-vlad"},"is_answered":false,"view_count":15,"answer_count":0,"score":0,"last_activity_date":1561405169,"creation_date":1561387145,"last_edit_date":1561405169,"question_id":56738916,"link":"https://stackoverflow.com/questions/56738916/attributeerror-when-running-callback-in-plotly-dash-library","title":"AttributeError when running callback in Plotly-Dash library"},{"tags":["python","django"],"owner":{"reputation":125,"user_id":4719092,"user_type":"registered","accept_rate":47,"profile_image":"https://lh4.googleusercontent.com/-qMqSvtGluLU/AAAAAAAAAAI/AAAAAAAAABU/7JjCBdRxWzc/photo.jpg?sz=128","display_name":"Jide Koso","link":"https://stackoverflow.com/users/4719092/jide-koso"},"is_answered":false,"view_count":656,"answer_count":2,"score":3,"last_activity_date":1561405077,"creation_date":1449555435,"question_id":34149274,"link":"https://stackoverflow.com/questions/34149274/django-streaminghttpresponse-deleting-file-after-user-finishes-downloading-it","title":"Django StreamingHttpResponse deleting file after user finishes downloading it"},{"tags":["python","mongodb","serialization"],"owner":{"reputation":1261,"user_id":6093604,"user_type":"registered","accept_rate":60,"profile_image":"https://i.stack.imgur.com/7f17S.jpg?s=128&g=1","display_name":"Emixam23","link":"https://stackoverflow.com/users/6093604/emixam23"},"is_answered":false,"view_count":16,"answer_count":1,"score":0,"last_activity_date":1561403836,"creation_date":1561133432,"question_id":56707041,"link":"https://stackoverflow.com/questions/56707041/unable-to-insert-nested-object-in-mongodb-using-pymongo","title":"Unable to insert nested object in mongodb using pymongo"},{"tags":["android","python-3.x","python-3.7","pyaudio","kindle"],"owner":{"reputation":1,"user_id":11682370,"user_type":"registered","profile_image":"https://lh3.googleusercontent.com/a-/AAuE7mCd9pTfbFXBCXTKg129AjBHgdC1b07lZ33nzjn81A?sz=128","display_name":"JD413","link":"https://stackoverflow.com/users/11682370/jd413"},"is_answered":false,"view_count":9,"answer_count":0,"score":0,"last_activity_date":1561399378,"creation_date":1561388514,"last_edit_date":1561399378,"question_id":56739352,"link":"https://stackoverflow.com/questions/56739352/cannot-install-pyaudio-using-pip-cannot-install-pyaudio-file-through-web-kindl","title":"Cannot install PyAudio using pip. Cannot install PyAudio file through web. Kindle/Fire OS Work around?"},{"tags":["beautifulsoup","html5lib"],"owner":{"reputation":9807,"user_id":1506338,"user_type":"registered","accept_rate":81,"profile_image":"https://i.stack.imgur.com/QWo3c.jpg?s=128&g=1","display_name":"Ehvince","link":"https://stackoverflow.com/users/1506338/ehvince"},"is_answered":true,"view_count":28936,"accepted_answer_id":38447762,"answer_count":6,"score":56,"last_activity_date":1561399029,"creation_date":1468887253,"last_edit_date":1514264778,"question_id":38447738,"link":"https://stackoverflow.com/questions/38447738/beautifulsoup-html5lib-module-object-has-no-attribute-base","title":"beautifulsoup, html5lib:&#160;module object has no attribute _base"},{"tags":["python","ansible","ansible-2.x"],"owner":{"reputation":25,"user_id":9482600,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/5e638be07d4b7d6246f701893177f03c?s=128&d=identicon&r=PG&f=1","display_name":"Radaeld","link":"https://stackoverflow.com/users/9482600/radaeld"},"is_answered":false,"view_count":41,"answer_count":0,"score":0,"last_activity_date":1561397545,"creation_date":1561302362,"last_edit_date":1561397545,"question_id":56725122,"link":"https://stackoverflow.com/questions/56725122/ansible-failing-when-being-used-async","title":"Ansible failing when being used async"},{"tags":["django"],"owner":{"reputation":155,"user_id":6390119,"user_type":"registered","accept_rate":50,"profile_image":"https://www.gravatar.com/avatar/17b48c084ee9e6afdea1c3efc0d59d82?s=128&d=identicon&r=PG&f=1","display_name":"Crazy Frog","link":"https://stackoverflow.com/users/6390119/crazy-frog"},"is_answered":true,"view_count":489,"answer_count":2,"score":1,"last_activity_date":1561396781,"creation_date":1487535028,"question_id":42332304,"link":"https://stackoverflow.com/questions/42332304/django-an-equality-check-in-annotate-clause","title":"Django - an equality check in annotate-clause"},{"tags":["python","json","anytree"],"owner":{"reputation":911,"user_id":2623411,"user_type":"registered","accept_rate":100,"profile_image":"https://i.stack.imgur.com/72X2w.png?s=128&g=1","display_name":"MikeS159","link":"https://stackoverflow.com/users/2623411/mikes159"},"is_answered":false,"view_count":8,"answer_count":0,"score":0,"last_activity_date":1561396603,"creation_date":1561396603,"question_id":56741217,"link":"https://stackoverflow.com/questions/56741217/using-anytree-to-convert-json-to-a-image","title":"Using anytree to convert JSON to a image"},{"tags":["python","pandas"],"owner":{"reputation":23,"user_id":11584648,"user_type":"registered","profile_image":"https://lh3.googleusercontent.com/-ZoPL7d0m9bg/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rcVi3y9FKZSm-JQyV4lYLOVtQYNMg/mo/photo.jpg?sz=128","display_name":"Brendan McDonald","link":"https://stackoverflow.com/users/11584648/brendan-mcdonald"},"is_answered":true,"view_count":31,"closed_date":1561400643,"accepted_answer_id":56739148,"answer_count":2,"score":0,"last_activity_date":1561393754,"creation_date":1561386878,"last_edit_date":1561388715,"question_id":56738839,"link":"https://stackoverflow.com/questions/56738839/filtering-a-dataframe-with-datetime-index-using-loc-rows-columns","closed_reason":"duplicate","title":"Filtering a dataframe with datetime index using .loc (rows &amp; columns)"},{"tags":["python","mysql","sqlalchemy"],"owner":{"reputation":1,"user_id":10337301,"user_type":"registered","profile_image":"https://lh5.googleusercontent.com/-VmF6__0g4TY/AAAAAAAAAAI/AAAAAAAAAQU/HdexL7IocUQ/photo.jpg?sz=128","display_name":"Za Shiva","link":"https://stackoverflow.com/users/10337301/za-shiva"},"is_answered":false,"view_count":7,"answer_count":0,"score":-1,"last_activity_date":1561393023,"creation_date":1561393023,"question_id":56740477,"link":"https://stackoverflow.com/questions/56740477/module-sqlalchemy-sql-sqltypes-has-no-attribute-nativeforemulated","title":"module &#39;sqlalchemy.sql.sqltypes&#39; has no attribute &#39;NativeForEmulated&#39;"},{"tags":["anaconda","pymc3"],"owner":{"reputation":8,"user_id":10771355,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/13807a67c63bcd979309c6041091d8be?s=128&d=identicon&r=PG&f=1","display_name":"George","link":"https://stackoverflow.com/users/10771355/george"},"is_answered":false,"view_count":17,"answer_count":1,"score":0,"last_activity_date":1561392131,"creation_date":1559793676,"last_edit_date":1561392131,"question_id":56470732,"link":"https://stackoverflow.com/questions/56470732/how-to-use-normal-constructor-correctly-in-pymc3","title":"How to use Normal constructor correctly in pymc3?"},{"tags":["python","seaborn"],"owner":{"reputation":92,"user_id":9451629,"user_type":"registered","profile_image":"https://lh4.googleusercontent.com/-mjZtk647a-M/AAAAAAAAAAI/AAAAAAAAAQY/NSIgGra_FdM/photo.jpg?sz=128","display_name":"AdeEla","link":"https://stackoverflow.com/users/9451629/adeela"},"is_answered":true,"view_count":17194,"accepted_answer_id":51422773,"answer_count":4,"score":11,"last_activity_date":1561391979,"creation_date":1532001534,"last_edit_date":1532001625,"question_id":51422146,"link":"https://stackoverflow.com/questions/51422146/install-the-latest-version-of-seaborn-0-9-0-through-pip","title":"Install the latest version of seaborn (0.9.0) through pip"},{"tags":["airflow"],"owner":{"reputation":198,"user_id":5236286,"user_type":"registered","accept_rate":71,"profile_image":"https://www.gravatar.com/avatar/501bf91cdd0d7745258ddc4f1a1cb932?s=128&d=identicon&r=PG&f=1","display_name":"Bo Qiang","link":"https://stackoverflow.com/users/5236286/bo-qiang"},"is_answered":false,"view_count":7,"answer_count":0,"score":0,"last_activity_date":1561390807,"creation_date":1561390807,"question_id":56739940,"link":"https://stackoverflow.com/questions/56739940/airflow-errors-out-when-trying-to-execute-remote-script-through-sshhook","title":"airflow errors out when trying to execute remote script through SSHHook"},{"tags":["python","scikit-learn","xgboost"],"owner":{"reputation":1,"user_id":7162020,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/e38d8ac36ecb2df766e4e2d3179dfa15?s=128&d=identicon&r=PG&f=1","display_name":"alanwatson","link":"https://stackoverflow.com/users/7162020/alanwatson"},"is_answered":false,"view_count":12,"answer_count":0,"score":0,"last_activity_date":1561388690,"creation_date":1561388690,"question_id":56739392,"link":"https://stackoverflow.com/questions/56739392/attributeerror-xgbclassifier-object-has-no-attribute-save-raw","title":"AttributeError: &#39;XGBClassifier&#39; object has no attribute &#39;save_raw&#39;"},{"tags":["python","django"],"owner":{"reputation":8,"user_id":11151969,"user_type":"registered","profile_image":"https://lh6.googleusercontent.com/-FHyof3pyWcc/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3reNJQ40JkKLcD9g44WeuB9YUBo1eg/mo/photo.jpg?sz=128","display_name":"mahesh chougule","link":"https://stackoverflow.com/users/11151969/mahesh-chougule"},"is_answered":true,"view_count":64,"accepted_answer_id":56730257,"answer_count":2,"score":1,"last_activity_date":1561388663,"creation_date":1561352649,"last_edit_date":1561352763,"question_id":56730111,"link":"https://stackoverflow.com/questions/56730111/attributeerror-list-object-has-no-attribute-iter-rows","title":"AttributeError: &#39;list&#39; object has no attribute &#39;iter_rows&#39;"},{"tags":["python","django","django-models"],"owner":{"reputation":7,"user_id":7426720,"user_type":"registered","profile_image":"https://graph.facebook.com/236747920099416/picture?type=large","display_name":"Veli Eroglu","link":"https://stackoverflow.com/users/7426720/veli-eroglu"},"is_answered":true,"view_count":12,"accepted_answer_id":56739203,"answer_count":1,"score":0,"last_activity_date":1561388120,"creation_date":1561387789,"last_edit_date":1561388120,"question_id":56739126,"link":"https://stackoverflow.com/questions/56739126/django-signals-module-object-has-no-attribute-post-save","title":"django signals module object has no attribute &#39;post_save&#39;"},{"tags":["python","meep"],"owner":{"reputation":11,"user_id":10523107,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/0377e0e9077cdaf19f46eb578d4cc4cf?s=128&d=identicon&r=PG&f=1","display_name":"A. Dragomir","link":"https://stackoverflow.com/users/10523107/a-dragomir"},"is_answered":false,"view_count":154,"answer_count":1,"score":1,"last_activity_date":1561388031,"creation_date":1539854926,"last_edit_date":1539856885,"question_id":52871023,"link":"https://stackoverflow.com/questions/52871023/attributeerror-module-meep-has-no-attribute-vector3","title":"AttributeError: module &#39;meep&#39; has no attribute &#39;Vector3&#39;"},{"tags":["python","pandas"],"owner":{"reputation":1,"user_id":5281138,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/df31f77cb4a7860a744726b4ab445abe?s=128&d=identicon&r=PG&f=1","display_name":"Shruti Bhatnagar","link":"https://stackoverflow.com/users/5281138/shruti-bhatnagar"},"is_answered":false,"view_count":38,"answer_count":2,"score":-2,"last_activity_date":1561383676,"creation_date":1561383197,"last_edit_date":1561383676,"question_id":56737733,"link":"https://stackoverflow.com/questions/56737733/what-is-wrong-with-my-code-i-wanted-to-see-the-transformations-i-did-instead-g","title":"what is wrong with my code ? i wanted to see the transformations i did instead getting the error meassage"},{"tags":["python","django","django-orm"],"owner":{"reputation":9974,"user_id":1331671,"user_type":"registered","accept_rate":96,"profile_image":"https://www.gravatar.com/avatar/0b78be3515d4822fcfa907b0f184a288?s=128&d=identicon&r=PG","display_name":"Ron","link":"https://stackoverflow.com/users/1331671/ron"},"is_answered":true,"view_count":7,"accepted_answer_id":56737785,"answer_count":1,"score":0,"last_activity_date":1561383401,"creation_date":1561383040,"question_id":56737688,"link":"https://stackoverflow.com/questions/56737688/django-creating-custom-queryset-for-relatedmanager","title":"django - Creating custom queryset for RelatedManager"},{"tags":["python","dataframe","ode"],"owner":{"reputation":1,"user_id":11692270,"user_type":"registered","profile_image":"https://www.gravatar.com/avatar/357d7746072f3a5fd713fb9f51d70101?s=128&d=identicon&r=PG&f=1","display_name":"blurr","link":"https://stackoverflow.com/users/11692270/blurr"},"is_answered":false,"view_count":30,"answer_count":0,"score":0,"last_activity_date":1561382461,"creation_date":1561380244,"last_edit_date":1561382461,"question_id":56736890,"link":"https://stackoverflow.com/questions/56736890/attributeerror-float-object-has-no-attribute-iloc-error-shown-for-datafra","title":"&#39;AttributeError: &#39;float&#39; object has no attribute &#39;iloc&#39;&#39; error shown for Dataframe"},{"tags":["python-3.x","postgresql","sqlalchemy"],"owner":{"reputation":8,"user_id":10359677,"user_type":"registered","profile_image":"https://lh6.googleusercontent.com/-7zUpjtBYBLs/AAAAAAAAAAI/AAAAAAAAAAA/APUIFaPZZ42zrbaaiUoT-oiZ06XnHnxM7w/mo/photo.jpg?sz=128","display_name":"Thomas Hobbes","link":"https://stackoverflow.com/users/10359677/thomas-hobbes"},"is_answered":false,"view_count":11,"answer_count":0,"score":0,"last_activity_date":1561382351,"creation_date":1561382351,"question_id":56737480,"link":"https://stackoverflow.com/questions/56737480/sqlalchemy-orm-query-object-returns-result-of-different-type-depending-on-contex","title":"sqlalchemy ORM query object returns result of different type depending on context"}],"has_more":true,"quota_max":300,"quota_remaining":247}')
